# set to a default 8080 port, but can be changed, if 8080 is occupied.
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
  file: connected-app.log

