# set to a default 8080 port, but ca be changed, if 8080 is occupied.
server:
  port: 8080


logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
  file: connected-app.log